
#服务器端口配置
  server:
    port: 8083
#修改banner
  spring:
    banner:
      location: banner.txt

    datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=Asia/Shanghai
          username: root
          password: pwd123


#日志相关  默认是info

  logging:
    level:
      root: info

#mybatis-p相关配置

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
    type-aliases-package: com.example.springboot_demo1.pojo
#      db-config:
#        设置表的统一前缀
#        table-prefix: tbl_
#        设置统一的主键自增策略
#        id-type: auto